### ISSUE TITLE
Exception with LinkedIn provider and play2-memcached plugin

### ISSUE THREAD

**Issue by EvanDooner** [joscha/play-authenticate#291]
We've switched our application cache from the default EHCache implementation to a memcached-based one, using the [play2-memcached](https://github.com/mumoshu/play2-memcached) plugin.

When trying to link a LinkedIn identity to an existing account, we're encountering the following exception:

```
play.api.Application$$anon$1: Execution exception[[NotSerializableException: com.feth.play.module.pa.user.EmploymentsIdentity$EmploymentInfo]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.5]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.5]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.5]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.5]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.5]
Caused by: java.io.NotSerializableException: com.feth.play.module.pa.user.EmploymentsIdentity$EmploymentInfo
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183) ~[na:1.7.0_91]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347) ~[na:1.7.0_91]
	at java.util.ArrayList.writeObject(ArrayList.java:742) ~[na:1.7.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_91]
```

I believe this is caused by the serialization engine used by the *play2-memached* plugin. The plugin uses Java serialization to serialize objects, and thus relies on the `Serializable` interface.

I have forked Play Authenticate, and intend to change `com.feth.play.module.pa.user.EmploymentsIdentity.EmploymentInfo` to implement the `Serializable` interface.

I'm raising this issue to make you aware of it, and ask if there would be interest in pulling this change back into master? 

I believe this is related to #276 , as that user is also using the *play2-memcached* plugin to add memcached support.

Affected Play version: 2.2.5

**Comment by joscha** [comment]
I am happy to merge any PR related to this issue coming along ;)

**Comment by joscha** [comment]
Pulled all the changes up. Will release new versions later. Snapshots should appear automatically, so if you could try one, that'd be great.

**Comment by EvanDooner** [comment]
About to try the 2.2.x snapshot now. I'll let you know how I get on.

**Comment by EvanDooner** [comment]
I'm not sure how to find the updated snapshots. I've downloaded the snapshot at http://joscha.github.com/play-authenticate/repo/snapshots/com.feth/play-authenticate_2.10/0.5.3-SNAPSHOT/jars/play-authenticate_2.10.jar, but it doesn't seem to have the updated code. Can you advise?

**Comment by joscha** [comment]
They are here: http://joscha.github.io/play-authenticate/repo/
Release `0.7.1`, `0.6.9`, `0.5.4` (thats the one you want) and `0.3.6`.

**Comment by csabaujvari** [comment]
After saw the #291 issue and updating play authenticate dependency to ```0.7.1```, we still have an exception when we try to login with LinkedIn provider. 

```java 
[error] - memcached.plugin - An error has occured while getting the value from memcached. ct=Any
java.util.concurrent.ExecutionException: java.io.InvalidClassException: com.feth.play.module.pa.providers.oauth1.OAuth1AuthProvider$SerializableRequestToken; no valid constructor
```

Affected Play version: 2.4.4

**Comment by joscha** [comment]
Can you write a test that shows this problem and/or provide a fix?

**Comment by csabaujvari** [comment]
I only found the line where it throws the exception:
```java
PlayAuthenticate.java:295
```
I will try to figure it out.
