### ISSUE TITLE
Sample app not running

### ISSUE THREAD

**Issue by ajaimesv** [joscha/play-authenticate#366]
Hello, I have just cloned the play-authenticate tree and cannot make it work. 

I keep getting the following exception:

`[error] io.ebean.Ebean - Error trying to create the default EbeanServer
java.lang.RuntimeException: DataSource user is null?
	at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:204)
	at org.avaje.datasource.Factory.createPool(Factory.java:12)
	at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:310)
	at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:265)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:108)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:79)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:44)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:55)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:201)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:159)`

And before that one, a big bunch of the following one:

`java.lang.IllegalArgumentException
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:185)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:168)
	at io.ebean.enhance.Transformer.detect(Transformer.java:292)
	at io.ebean.enhance.Transformer.transform(Transformer.java:113)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
	at play.ebean.sbt.PlayEbean$$anonfun$ebeanEnhance$1.apply(PlayEbean.scala:74)
	at play.ebean.sbt.PlayEbean$$anonfun$ebeanEnhance$1.apply(PlayEbean.scala:46)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)`

I have tried several things but nothing has worked. Is anyone else having this issue?

Thanks

**Comment by adpes** [comment]
I experience [samples/java/play-authenticate-usage](/joscha/play-authenticate/tree/3f70e0316b5a848b78cd3e47c80f431d6de1afc9/samples/java/play-authenticate-usage) building and running on https://github.com/joscha/play-authenticate/commit/3f70e0316b5a848b78cd3e47c80f431d6de1afc9.
Which sample app did you test on which commit?
